
# Mensagens
OPCAO_INVALIDA = 'OPÇÃO INVÁLIDA !!!\n'
INIMIGO_FORA_DA_LISTA = 'INIMIGO NÃO SE ENCONTRA NA LISTA !!!\n'
NUMERO_INVALIDO = 'NÚMERO INVÁLIDO !!!\n'
TITULO_REGRA = '.::..::| INSTRUÇÕES/REGRAS |::..::.'
PRESSIONE_ENTER = '\n\n.::| PRESSIONE ENTER PARA COMEÇAR |::.\n'
